# Generated by Django 3.1.6 on 2021-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210217_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('EST', 'Estandar'), ('NIP', 'No imponible'), ('PDG', 'Producto digital')], default=('EST', 'Estandar'), max_length=200, null=True),
        ),
    ]
